name: 'Hax Auto Renew'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 */1 * *'
  watch:
    types: [started]
jobs:
  hax_renew:
    runs-on: windows-2022
    
    steps:
      - name: 'Renewing Hax VPS ....' 
        run: |
          cmd /c curl -sSL -O https://github.com/SAKURA-KIMI/autoextend/raw/main/HaxAutoReNew.exe
          cmd /c HaxAutoReNew.exe -user "${{ secrets.USER }}" -password "${{ secrets.PASSWORD }}"
